export const RIGHT_MEDICALSERVICES = 121401;
export const RIGHT_MEDICALSERVICES_ADD = 121402;
export const RIGHT_MEDICALSERVICES_EDIT = 121403;
export const RIGHT_MEDICALSERVICES_DELETE = 121404;
export const RIGHT_MEDICALLABSERVICES = 128301;
export const RIGHT_MEDICALLABSERVICES_ADD = 128302;
export const RIGHT_MEDICALLABSERVICES_EDIT = 121402;
export const RIGHT_MEDICALLABSERVICES_DELETE = 128304;
export const RIGHT_MEDICALITEMS = 122101;
export const RIGHT_MEDICALITEMS_ADD = 122102;
export const RIGHT_MEDICALITEMS_EDIT = 122103;
export const RIGHT_MEDICALITEMS_DELETE = 122104;

export const LAB_SERVICES_MODULE_NAME = "medicalLabServices";

export const VISIT_TYPES = ["E", "O", "R"];

export const CARE_TYPE_INPATIENT = "I";
export const CARE_TYPE_OUTPATIENT = "O";
export const CARE_TYPE_BOTH = "B";
export const CARE_TYPES = [CARE_TYPE_INPATIENT, CARE_TYPE_OUTPATIENT, CARE_TYPE_BOTH];

export const SERVICE_TYPE_PREVENTATIVE = "P";
export const SERVICE_TYPE_CURATIVE = "C";
export const SERVICE_TYPES = [SERVICE_TYPE_PREVENTATIVE, SERVICE_TYPE_CURATIVE];


export const SERVICE_TYPE_PP_S = "S";
export const SERVICE_TYPE_PP_P = "P";
export const SERVICE_TYPE_PP_F = "F";
export const SERVICE_TYPES_PP = [SERVICE_TYPE_PP_S, SERVICE_TYPE_PP_P, SERVICE_TYPE_PP_F];


export const ITEM_TYPE_DRUG = "D";
export const ITEM_TYPE_MEDICAL_CONSUMABLE = "M";
export const ITEM_TYPES = [ITEM_TYPE_DRUG, ITEM_TYPE_MEDICAL_CONSUMABLE];

export const SERVICE_CODE_MAX_LENGTH = 6;
export const ITEM_CODE_MAX_LENGTH = 6;

export const SERVICE_CATEGORY_SURGERY = "S";
export const SERVICE_CATEGORY_DELIVERY = "D";
export const SERVICE_CATEGORY_ANTENATAL = "A";
export const SERVICE_CATEGORY_HOSPITALIZATION = "H";
export const SERVICE_CATEGORY_CONSULTATION = "C";
export const SERVICE_CATEGORY_OTHER = "O";
export const SERVICE_CATEGORY_VISIT = "V";
export const SERVICE_CATEGORY_ANESTHESIA = 1;
export const SERVICE_CATEGORY_CIRCUMCISION = 2;
export const SERVICE_CATEGORY_DENTAL_PROCEDURES = 3;
export const SERVICE_CATEGORY_DERMATOLOGY = 4;
export const SERVICE_CATEGORY_ENT_PROCEDURES = 5;
export const SERVICE_CATEGORY_GASTROINTESTINAL_AND_COLORECTAL = 6;
export const SERVICE_CATEGORY_GENERAL_SURGERY = 7;
export const SERVICE_CATEGORY_GENITOURINARY = 8;
export const SERVICE_CATEGORY_GYN_OBS_PROCEDURES = 9;
export const SERVICE_CATEGORY_LIFE_SUPPORT_COURSES = 10;
export const SERVICE_CATEGORY_MATERNITY_CARE = 11;
export const SERVICE_CATEGORY_MAXILOFACIAL_PROCEDURES = 12;
export const SERVICE_CATEGORY_MEDICAL = 13;
export const SERVICE_CATEGORY_MEDICAL_OPD = 14;
export const SERVICE_CATEGORY_MUSCULOSKELETAL = 15;
export const SERVICE_CATEGORY_NEURO_SURGERY = 16;
export const SERVICE_CATEGORY_ORTHOPEDIC_PROCEDURES = 17;
export const SERVICE_CATEGORY_PLASTIC_AND_RECONSTRUCTION_PROCEDURES = 18;
export const SERVICE_CATEGORY_PULMONARY_ULTRASOUND = 19;
export const SERVICE_CATEGORY_SKIN = 20;
export const SERVICE_CATEGORY_SURGICAL = 21;
export const SERVICE_CATEGORY_URGENT_CARE_AND_HOSPITAL = 22;
export const SERVICE_CATEGORY_UROLOGY_PROCEDURE = 23;
export const SERVICE_CATEGORY_WOMENS_HEALTH = 24;
export const SERVICE_CATEGORY_X_RAY = 25;
export const SERVICE_CATEGORY_WOUND_DRESSING_SMALL_TO_MEDIUM = 26;

export const SERVICE_CATEGORIES = [
  SERVICE_CATEGORY_ANESTHESIA,
  SERVICE_CATEGORY_CIRCUMCISION,
  SERVICE_CATEGORY_DENTAL_PROCEDURES,
  SERVICE_CATEGORY_DERMATOLOGY,
  SERVICE_CATEGORY_ENT_PROCEDURES,
  SERVICE_CATEGORY_GASTROINTESTINAL_AND_COLORECTAL,
  SERVICE_CATEGORY_GENERAL_SURGERY,
  SERVICE_CATEGORY_GENITOURINARY,
  SERVICE_CATEGORY_GYN_OBS_PROCEDURES,
  SERVICE_CATEGORY_LIFE_SUPPORT_COURSES,
  SERVICE_CATEGORY_MATERNITY_CARE,
  SERVICE_CATEGORY_MAXILOFACIAL_PROCEDURES,
  SERVICE_CATEGORY_MEDICAL,
  SERVICE_CATEGORY_MEDICAL_OPD,
  SERVICE_CATEGORY_MUSCULOSKELETAL,
  SERVICE_CATEGORY_NEURO_SURGERY,
  SERVICE_CATEGORY_ORTHOPEDIC_PROCEDURES,
  SERVICE_CATEGORY_PLASTIC_AND_RECONSTRUCTION_PROCEDURES,
  SERVICE_CATEGORY_PULMONARY_ULTRASOUND,
  SERVICE_CATEGORY_SKIN,
  SERVICE_CATEGORY_SURGICAL,
  SERVICE_CATEGORY_URGENT_CARE_AND_HOSPITAL,
  SERVICE_CATEGORY_UROLOGY_PROCEDURE,
  SERVICE_CATEGORY_WOMENS_HEALTH,
  SERVICE_CATEGORY_X_RAY,
  SERVICE_CATEGORY_WOUND_DRESSING_SMALL_TO_MEDIUM
];

export const SERVICE_LEVEL_SIMPLE_SERVICE = "S";
export const SERVICE_LEVEL_VISIT = "V";
export const SERVICE_LEVEL_DAY_HOSPITAL = "D";
export const SERVICE_LEVEL_HOSPITAL_CARE = "H";
export const SERVICE_LEVELS = [
  SERVICE_LEVEL_SIMPLE_SERVICE,
  SERVICE_LEVEL_VISIT,
  SERVICE_LEVEL_DAY_HOSPITAL,
  SERVICE_LEVEL_HOSPITAL_CARE,
];

export const PATIENT_CATEGORY_MASK_MALE = 1;
export const PATIENT_CATEGORY_MASK_FEMALE = 2;
export const PATIENT_CATEGORY_MASK_ADULT = 4;
export const PATIENT_CATEGORY_MASK_MINOR = 8;

export const GENDER_CATEGORIES = [
  PATIENT_CATEGORY_MASK_MALE,
  PATIENT_CATEGORY_MASK_FEMALE,
];
export const AGE_CATEGORIES = [
  PATIENT_CATEGORY_MASK_ADULT,
  PATIENT_CATEGORY_MASK_MINOR,
];

export const PATIENT_CATEGORIES = [
  PATIENT_CATEGORY_MASK_MALE,
  PATIENT_CATEGORY_MASK_FEMALE,
  PATIENT_CATEGORY_MASK_ADULT,
  PATIENT_CATEGORY_MASK_MINOR,
];

export const MANUAL_PRICE = [ 0, 1 ];
export const ITEMS_MODULE_NAME = "medicalItem";
export const SERVICES_MODULE_NAME = "medicalService";
